# Generated by Django 4.2.16 on 2024-10-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('preferred_language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(default=0)),
                ('is_company_owner', models.BooleanField(default=False)),
                ('is_invited_user', models.BooleanField(default=False)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
