# Generated by Django 4.2.16 on 2024-10-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='is_invited_user',
            new_name='is_invited_user_company',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='is_invited_user_partner',
            field=models.BooleanField(default=False),
        ),
    ]
