# Generated by Django 4.2.16 on 2024-10-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_rename_is_invited_user_usersettings_is_invited_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='os',
            field=models.CharField(default='', max_length=15),
        ),
    ]
