# Generated by Django 4.2.16 on 2024-10-18 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_street', models.CharField(max_length=100)),
                ('partner_house_number', models.CharField(max_length=100)),
                ('partner_city', models.CharField(max_length=100)),
                ('partner_country', models.CharField(max_length=100)),
                ('partner_phone', models.CharField(max_length=100)),
                ('partner_email', models.EmailField(max_length=100)),
                ('partner_zip', models.CharField(max_length=100)),
                ('partner_created_at', models.DateTimeField(auto_now_add=True)),
                ('partner_updated_at', models.DateTimeField(auto_now=True)),
                ('partner_blocked', models.BooleanField(default=False)),
                ('partner_owner', models.ManyToManyField(related_name='owned_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
