# Generated by Django 4.2.16 on 2024-10-18 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_partner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation',
            new_name='InvitationCompany',
        ),
    ]
