# Generated by Django 4.2.16 on 2024-10-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_invitation_invitationcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
