# Generated by Django 4.2.16 on 2024-10-18 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_invitationpartnertocreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationpartnertocreate',
            name='partner_to_create_used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitationpartnertocreate',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
