# Generated by Django 4.2.16 on 2024-10-29 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_alter_invitationpartnertocreate_partner_to_create_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exmembers',
            name='executed_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='executer_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
