# Generated by Django 4.2.16 on 2024-10-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_invitationpartner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationpartner',
            old_name='company',
            new_name='partner',
        ),
    ]
