# Generated by Django 4.2.16 on 2024-10-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_invitationcompany_company_used_by_and_more'),
        ('partner', '0003_rename_company_invitationpartner_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='company.company'),
        ),
    ]
