# Generated by Django 4.2.16 on 2024-10-28 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0004_partner_partner_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationpartner',
            name='partner_to_invite_used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_invited_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
