# Generated by Django 4.2.16 on 2024-10-28 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0005_invitationpartner_partner_to_invite_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_staff',
            field=models.ManyToManyField(blank=True, related_name='staff_partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
