# Generated by Django 4.2.16 on 2024-10-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_partner_partner_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationpartner',
            old_name='partner_to_invite_used_by',
            new_name='partner_to_create_used_by',
        ),
    ]
