# Generated by Django 4.2.16 on 2024-10-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0008_exmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False)),
                ('lead_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lead_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('lead_status', models.CharField(default='open', max_length=100)),
                ('creator', models.ManyToManyField(related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='partner.partner')),
            ],
        ),
    ]
