# Generated by Django 4.2.16 on 2024-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('open', 'Offen'), ('won', 'Gewonnen'), ('lost', 'Verloren')], default='open', max_length=100),
        ),
    ]
