# Generated by Django 4.2.16 on 2024-11-13 12:04

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0010_alter_lead_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_adress', models.CharField(max_length=100)),
                ('contact_phonenumber', models.CharField(max_length=100)),
                ('contact_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('contact_created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_updated_at', models.DateTimeField(auto_now=True)),
                ('contact_status', models.CharField(default='open', max_length=100)),
                ('contact_position', models.CharField(max_length=100)),
                ('connected_lead', models.ManyToManyField(related_name='contacts', to='partner.lead')),
                ('contact_creator', models.ManyToManyField(related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
